### ISSUE TITLE
How to change configuration of peripherals (geo scanner)

### ISSUE THREAD

**Issue by promitheas-nikou** [IntelligenceModding/Advanced-Peripherals-Documentation#49]
### Describe

I noticed that a geoscanner can be used on a pocket computer, and that it can be used to very locate a lot of ores/rare blocks, mainly because of its short cooldown and huge range. Is there any way to change them? I looked in the configs but found nothing useful. The documentation says nothing either

PS minecraft 1.19.2 mod ver 0.7.21b

### Steps to reproduce

1. I don't know
2. Why I have to
3. Write this

### Direct URL

https://advancedperipherals.madefor.cc/1.19/peripherals/geo_scanner/

**Comment by SirEndii** [comment]
> I don't know
> Why I have to
> Write this

Because this is the wrong repository
You report bugs here for the documentation
If you have questions, use the discussions on our repo https://github.com/SirEndii/AdvancedPeripherals
Or join the discord https://discord.intelligence-modding.de

And nope, there are currently no configuration options for this
